### ISSUE TITLE
What about @ char in key vars?

### ISSUE THREAD

**Issue by quivalen** [damphat/kv-bash#5]
@ Is an invalid symbol atm in keys in kv-bash.
I've added @ to the regexp and kv-test pass all the tests.

Is there any specific reason @ simbol was excluded from allowed key ?

**Comment by damphat** [comment]
kvbash store keys as  filenames and I am not sure that all FAT types accept '@'.   
For safety, I use white-list characters (alpha numberic : _ - . ) instead of black-list list characters ('\0' and '/')
If you want to use '@' in key, open kv-bash in editor, add '@' to the white-list:

```
kv_validate_key() {
	[[ "$1" =~ ^[0-9a-zA-Z._:@-]+$  ]]
}
```
Make a pull-request if you know how to check for valid filename. :)

**Comment by quivalen** [comment]
I didn't knew you were aiming for portability through filesystems. That makes sense.

Probably the unique way to be sure about legal file name is try to "touch" it and control the return code of the touch invocation. This add a bit of overhead to the whole thing. For my needs adding the '@' in kv-bash was enough, i'm closing the issue, cause you've explained the problem and people can read the answer here if they search a bit.

Thanks for the project btw :+1:
